/**
 * JSON-LD script tag.
 *
 * The Next.js-recommended pattern for embedding structured data is to
 * inject a static JSON-stringified object inside a <script type="application/
 * ld+json">. The data is generated by trusted source code (no user input),
 * so XSS is not a concern here. See:
 *   https://nextjs.org/docs/app/guides/json-ld
 *
 * Wrapping the pattern in this small helper keeps the call sites readable
 * and lets us audit one place if the schema shape ever needs sanitisation.
 */

type Props = {
  /** Plain object that will be JSON.stringify'd into the script tag */
  data: Record<string, unknown>;
};

export function JsonLd({ data }: Props) {
  const html = { __html: JSON.stringify(data) };
  // eslint-disable-next-line react/no-danger -- static JSON-LD payload from trusted source code
  return <script type="application/ld+json" dangerouslySetInnerHTML={html} />;
}
